create extension if not exists pgcrypto;

create table if not exists public.todo (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  todo text not null,
  note text,
  due_date date,
  completed boolean not null default false
);

alter table public.todo add column if not exists note text;
alter table public.todo add column if not exists due_date date;
alter table public.todo add column if not exists completed boolean not null default false;

create table if not exists public.memories (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  title text not null,
  story text not null,
  memory_date date not null default current_date,
  image_url text,
  image_path text
);

alter table public.todo enable row level security;
alter table public.memories enable row level security;

drop policy if exists "public can read todo" on public.todo;
drop policy if exists "public can insert todo" on public.todo;
drop policy if exists "public can update todo" on public.todo;
drop policy if exists "public can delete todo" on public.todo;

create policy "public can read todo"
on public.todo for select
to anon
using (true);

create policy "public can insert todo"
on public.todo for insert
to anon
with check (true);

create policy "public can update todo"
on public.todo for update
to anon
using (true)
with check (true);

create policy "public can delete todo"
on public.todo for delete
to anon
using (true);

drop policy if exists "public can read memories" on public.memories;
drop policy if exists "public can insert memories" on public.memories;
drop policy if exists "public can delete memories" on public.memories;

create policy "public can read memories"
on public.memories for select
to anon
using (true);

create policy "public can insert memories"
on public.memories for insert
to anon
with check (true);

create policy "public can delete memories"
on public.memories for delete
to anon
using (true);

insert into storage.buckets (id, name, public)
values ('memory-images', 'memory-images', true)
on conflict (id) do nothing;

drop policy if exists "public can view memory images" on storage.objects;
drop policy if exists "public can upload memory images" on storage.objects;
drop policy if exists "public can delete memory images" on storage.objects;

create policy "public can view memory images"
on storage.objects for select
to anon
using (bucket_id = 'memory-images');

create policy "public can upload memory images"
on storage.objects for insert
to anon
with check (bucket_id = 'memory-images');

create policy "public can delete memory images"
on storage.objects for delete
to anon
using (bucket_id = 'memory-images');
